openapi: 3.0.3
info:
  title: AgGateway Shipped Item Instance
  description: Allows the Retailer to send information about the actual product shipped to the Farmer, including shipment identifer, product identifiers, seed lot id, mixture batch id, seed treatment and product composition.  Allows the Farmer (via a mobile application or FMIS), or the Farmer's equipment manufacturer application (aka OEM Platform, e.g., Deere Operations Center, AGCO Fuse, CNH AFS, etc.) to retrieve the Product shipped by a Retailer using GET /setupfiles.   
  version: '3.0'
servers:
  - url: https://shipped-item-instance.azure-api.net/wg01
paths:
  /in-field-product-id/v3/setup-files:
    get:
      summary: GET a zipped file of setup files to load into the tractor display
      description: Using the shipment identifier and retailer's GLN, the API will return an octet-stream of zip file containing either ISOBUS XML or the ADAPT ADM protobuf formatted files.
      operationId: get-setupfiles
      tags:
        - Tractor display setup files
      parameters:
        - name: shipmentId
          in: query
          description: shipment identifier generated by the retailer's system of the product shipped to the farmer.
          required: true
          schema:
            type: string
        - name: retailerId
          in: query
          description: the GLN identifier of the retailer that shipped the product to the farmer.
          required: true
          schema:
            type: string
        - name: content-type
          in: header
          description: the content type that should be returned in the response.
          required: true
          schema:
            enum:
              - application/vnd.aggateway.adapt.adm+zip
              - application/vnd.aggateway.adapt.iso+zip
            type: string
            default: application/vnd.aggateway.adapt.iso+zip
      responses:
        '200':
          description: OAGIS JSON as profiled in Score by AgGateway
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                example: binaryCharacters
  /in-field-product-id/v3/shipped-item-instance:
    get:
      summary: GET JSON from NoSQL Database
      description: Using the shipment identifier and retailer's GLN, the API will return the original JSON that an array of items shipped from a retailer to the farmer.
      operationId: get-shippediteminstance
      tags:
        - Shipped Item Instance
      parameters:
        - name: shipmentId
          in: query
          description: shipment identifier generated by the retailer's system of the product shipped to the farmer.
          required: true
          schema:
            type: string
        - name: retailerId
          in: query
          description: the GLN identifier of the retailer that shipped the product to the farmer.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OAGIS JSON as profiled in Score by AgGateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/shippedItemInstance'
    post:
      summary: POST JSON to NoSQL Database
      description: ''
      operationId: post-shippediteminstance
      tags:
        - Shipped Item Instance
      requestBody:
        description: OAGIS JSON as profiled in Score by AgGateway
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shippedItemInstance'
      responses:
        '200':
          description: 'returns the NoSQL DB id generated on insert'
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                        type: string
                        description: unique systematically generated id
                        example: 9e944f86-1038-4ffa-b1ec-aefb6bb0c8b0
    patch:
      summary: Update ShippedItemInstance with the receive date
      description: Using the shipment identifier and retailer's GLN, the API will update the original JSON with the actual receive date, completing the transport event (CTE).
      operationId: patch-shippediteminstance
      tags:
        - Shipped Item Instance
      parameters:
        - name: shipmentId
          in: query
          description: shipment identifier generated by the retailer's system of the product shipped to the farmer.
          required: true
          schema:
            type: string
        - name: retailerId
          in: query
          description: the GLN identifier of the retailer that shipped the product to the farmer.
          required: true
          schema:
            type: string
        - name: actualDeliveryDateTime
          in: query
          description: the actual delivery date time, which will be when there is a scan of the delivery document.
          required: true
          schema:
            type: string
            format: "date-time"
      responses:
        '200':
          description: 'Returns the id updated'
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                        type: string
                        description: unique systematically generated id
                        example: 9e944f86-1038-4ffa-b1ec-aefb6bb0c8b0
  /in-field-product-id/v3/shipped-item-instance/{id}:
    put:
      summary: PUT an updated JSON to NoSQL Database
      description: ''
      operationId: put-shippediteminstance
      tags:
        - Shipped Item Instance
      parameters:
        - name: id
          in: path
          description: This is the id that was returned by the post-shippediteminstance operation.
          required: true
          schema:
            type: string
            example: 9e944f86-1038-4ffa-b1ec-aefb6bb0c8b0
      requestBody:
        description: OAGIS JSON as profiled in Score by AgGateway
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shippedItemInstance'
      responses:
        '200':
          description: 'Returns the id updated'
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                        type: string
                        description: unique systematically generated id
                        example: 9e944f86-1038-4ffa-b1ec-aefb6bb0c8b0
    delete:
      summary: DELETE JSON from NoSQL Database
      description: ''
      operationId: delete-shippediteminstance
      tags:
        - Shipped Item Instance
      parameters:
        - name: id
          in: path
          description: This is the id that was returned by the post-shippediteminstance operation.
          required: true
          schema:
            type: string
            example: 9e944f86-1038-4ffa-b1ec-aefb6bb0c8b0
      responses:
        '200':
          description: Returns the id deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                        type: string
                        description: unique systematically generated id
                        example: 9e944f86-1038-4ffa-b1ec-aefb6bb0c8b0
